# Dockerfile
FROM mcr.microsoft.com/devcontainers/universal:2

# Install prerequisites
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    openjdk-21-jdk \
    rlwrap \
    postgresql-client \
    odbc-postgresql \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Clojure CLI using the official script
RUN curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh && \
    chmod +x linux-install.sh && \
    ./linux-install.sh && \
    rm linux-install.sh

# Install babashka using the official script
# RUN bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)

RUN \
    # configure git to get rid of detached head warnings
    git config --global advice.detachedHead false; \
    git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch v0.15.0; \
    /bin/bash -c 'echo -e "\n\n## Configure ASDF \n. $HOME/.asdf/asdf.sh" >> ~/.bashrc'; \
    /bin/bash -c 'echo -e "\n\n## ASDF Bash Completion: \n. $HOME/.asdf/completions/asdf.bash" >> ~/.bashrc'; \
    exec bash;

# Set the working directory
WORKDIR /workspaces/driver-examples
