[tools]
node = "lts"

[tasks.default]
depends = ["run"]

[tasks.deps]
description = "Install Node.js dependencies"
run = "npm install"

[tasks.run]
description = "Run Node.js example"
depends = ["deps"]
run = "npm start"

[tasks.test]
description = "Run Node.js tests"
depends = ["deps"]
run = "node --test test/*.test.mjs"
