[tools]
"github:babashka/babashka" = "latest"

[tasks.default]
depends = ["run"]

[tasks.run]
description = "Run Babashka example"
run = "mise exec -- bb -m my-project.main"

[tasks.test]
description = "Run Babashka tests"
run = "mise exec -- bb run_tests.clj"
