[tools]
java = "21"
maven = "latest"

[tasks.default]
depends = ["run"]

[tasks.run]
description = "Run Kotlin example"
run = "./gradlew run"

[tasks.test]
description = "Run Kotlin tests"
run = "./gradlew test"
