# PHP uses system package manager installation

[tasks.default]
depends = ["run"]

[tasks.setup]
description = "Install PHP and ext-pq (PECL pq) extension"
run = """
# Install PHP if not present
if ! command -v php &> /dev/null; then
  echo "Installing PHP..."
  sudo pacman -S --noconfirm php
fi

# Install development tools needed for ext-pq compilation
if ! pacman -Q base-devel &> /dev/null; then
  echo "Installing build tools (base-devel)..."
  sudo pacman -S --noconfirm base-devel
fi

# Install PostgreSQL client libraries (required by ext-pq)
if ! pacman -Q postgresql-libs &> /dev/null; then
  echo "Installing PostgreSQL client libraries..."
  sudo pacman -S --noconfirm postgresql-libs
fi

# Enable required PHP extensions
if ! php -m | grep -q iconv; then
  echo "Enabling iconv extension..."
  sudo sed -i 's/;extension=iconv/extension=iconv/' /etc/php/php.ini
fi

# Install ext-pq using PECL
if ! php -m | grep -q pq; then
  echo "Installing ext-pq via PECL..."

  # Install PECL if not available
  if ! command -v pecl &> /dev/null; then
    echo "Installing PEAR/PECL..."
    curl -sS https://pear.php.net/go-pear.phar -o /tmp/go-pear.phar
    echo "" | php /tmp/go-pear.phar
    export PATH="$HOME/pear/bin:$PATH"
    rm /tmp/go-pear.phar
  fi

  # Add pecl to PATH if it's in ~/pear/bin
  if [ -f "$HOME/pear/bin/pecl" ]; then
    export PATH="$HOME/pear/bin:$PATH"
  fi

  # Get pecl path
  PECL_BIN="$HOME/pear/bin/pecl"

  # Install raphf dependency first
  if ! php -m | grep -q raphf; then
    echo "Installing raphf extension (required by ext-pq)..."
    sudo "$PECL_BIN" install raphf
    echo "extension=raphf" | sudo tee /etc/php/conf.d/raphf.ini > /dev/null
  fi

  # Install ext-pq
  sudo "$PECL_BIN" install pq

  echo "✓ ext-pq installed via PECL"
fi

# Enable pq extension if installed
if [ -f /usr/lib/php/modules/pq.so ] || [ -f /usr/local/lib/php/extensions/*/pq.so ]; then
  if ! php -m | grep -q pq; then
    echo "Enabling pq extension..."
    echo "extension=pq.so" | sudo tee /etc/php/conf.d/pq.ini > /dev/null
  fi
fi

# Verify ext-pq is loaded
if php -m | grep -q pq; then
  echo "✓ ext-pq successfully installed and enabled"
else
  echo "⚠ ext-pq not available - some tests will be skipped"
fi
"""

[tasks.deps]
description = "Install PHP dependencies"
run = """
mise run setup
if [ -f composer.json ]; then
  if [ -f composer.phar ]; then
    php composer.phar install
  elif command -v composer &> /dev/null; then
    composer install
  else
    echo "ERROR: composer not found. Please install composer first."
    exit 1
  fi
fi
"""

[tasks.run]
description = "Run PHP example"
depends = ["setup"]
run = "php XtdbHelloWorld.php"

[tasks.test]
description = "Run PHP tests"
depends = ["deps"]
run = "vendor/bin/phpunit"
