# PHP uses system package manager installation

[tasks.default]
depends = ["run"]

[tasks.setup]
description = "Install PHP and pgsql extension if needed"
run = """
if ! command -v php &> /dev/null; then
  echo "Installing PHP and php-pgsql extension..."
  sudo pacman -S --noconfirm php php-pgsql
elif ! php -m | grep -q pgsql; then
  echo "Installing php-pgsql extension..."
  sudo pacman -S --noconfirm php-pgsql
fi

# Enable pgsql extension if not already enabled
if ! php -m | grep -q pgsql; then
  echo "Enabling pgsql extension..."
  echo "extension=pgsql" | sudo tee /etc/php/conf.d/pgsql.ini > /dev/null
  echo "extension=pdo_pgsql" | sudo tee -a /etc/php/conf.d/pgsql.ini > /dev/null
fi
"""

[tasks.deps]
description = "Install PHP dependencies"
run = """
mise run setup
if [ -f composer.json ]; then
  if [ -f composer.phar ]; then
    php composer.phar install
  elif command -v composer &> /dev/null; then
    composer install
  else
    echo "ERROR: composer not found. Please install composer first."
    exit 1
  fi
fi
"""

[tasks.run]
description = "Run PHP example"
depends = ["setup"]
run = "php XtdbHelloWorld.php"

[tasks.test]
description = "Run PHP tests"
depends = ["deps"]
run = "vendor/bin/phpunit"
